-- P2: external verification results hang off loan_application (no separate KYC aggregate).
-- One row per (application, check_type); the unique constraint is the idempotency key.
create table application_verification (
    id              bigint generated by default as identity primary key,
    application_id  bigint not null,
    check_type      varchar(40) not null,
    status          varchar(20) not null,
    provider        varchar(40),
    provider_txn_id varchar(120),
    client_ref_num  varchar(120),
    name_match      double precision,
    score           bigint,
    s3_object_key   varchar(512),
    raw_response    jsonb,
    derived         jsonb,
    message         varchar(1000),
    created_at      timestamp(6) with time zone not null,
    created_by      varchar(255),
    updated_at      timestamp(6) with time zone,
    updated_by      varchar(255),
    constraint uq_application_verification unique (application_id, check_type)
);

create index ix_application_verification_application on application_verification (application_id);

-- S3 migration for documents: bytes move to S3, keyed by s3_object_key. Invariant
-- (enforced in the app): exactly one of data / s3_object_key is set. Existing rows keep
-- their inline bytea (read-only fallback), so data becomes nullable.
alter table application_document add column s3_object_key varchar(512);
alter table application_document alter column data drop not null;
