-- P8: admin-editable company payment block (the payee shown on the borrower repay screen).
-- Singleton table — exactly one row, edited by ADMIN. Seeded with the values that were
-- previously hardcoded on the repay page. The two *_object_key columns hold S3 keys for the
-- uploaded UPI QR image and payee account-info PDF (null until an admin uploads them; the UI
-- falls back to a bundled static asset). V17 is reserved for the auth phase.
create table payment_settings (
    id                       bigint generated by default as identity primary key,
    upi_id                   varchar(120),
    account_name             varchar(160),
    account_number           varchar(40),
    ifsc                     varchar(20),
    bank_name                varchar(120),
    qr_object_key            varchar(512),
    account_info_object_key  varchar(512),
    created_at               timestamp(6) with time zone not null,
    created_by               varchar(255),
    updated_at               timestamp(6) with time zone,
    updated_by               varchar(255)
);

insert into payment_settings (upi_id, account_name, account_number, ifsc, bank_name, created_at)
values ('navix.collections@hdfcbank', 'NAVIX Finance', '5010 0099 8877', 'HDFC0000123', 'HDFC Bank', now());
