-- V21: notification core — the two tables behind the in-app / SMS / email engine.
-- FK-light per the project convention (index notification_id instead of a FK). The partial index
-- powers the hot unread-count query. Independent of V22 (applicant_profile.email); ordered by number.

create table notification (
    id              bigint generated by default as identity primary key,
    recipient_type  varchar(16)   not null,         -- STAFF | BORROWER
    recipient_id    bigint        not null,          -- staff id or applicant id (the in-app inbox owner)
    type            varchar(64)   not null,          -- NotificationType name (template key)
    category        varchar(32)   not null,
    title           varchar(200)  not null,
    body            varchar(2000) not null,
    in_app          boolean       not null default true,
    read_at         timestamptz,
    application_id  bigint,
    loan_id         bigint,
    case_id         uuid,
    actor_id        varchar(64),
    actor_role      varchar(64),
    dedupe_key      varchar(120),                    -- optional idempotency guard (unused in v1)
    created_at      timestamptz   not null default now()
);

create index ix_notif_owner on notification (recipient_type, recipient_id, created_at desc);
create index ix_notif_unread on notification (recipient_type, recipient_id)
    where in_app and read_at is null;

create table notification_delivery (
    id              bigint generated by default as identity primary key,
    notification_id bigint        not null,
    channel         varchar(16)   not null,          -- IN_APP | SMS | EMAIL
    address         varchar(320),                    -- email / mobile actually used (null for IN_APP)
    status          varchar(16)   not null,          -- PENDING | SENT | FAILED | SKIPPED
    provider_ref    varchar(160),
    error           varchar(1000),
    attempts        int           not null default 0,
    created_at      timestamptz   not null default now(),
    updated_at      timestamptz
);

create index ix_notif_delivery_notification on notification_delivery (notification_id);
