-- V24: company expense ledger — ADMIN-tracked operating expenses (description, amount, payee, notes).
-- One flat table; money is integer paise (bigint). Audit columns mirror BaseAuditEntity. FK-light
-- (no foreign keys in this schema by convention).
create table company_expense (
    id           bigint generated by default as identity primary key,
    description  varchar(300)  not null,
    amount_paise bigint        not null,
    paid_to      varchar(200)  not null,
    notes        varchar(1000),
    expense_date date          not null,
    created_at   timestamptz   not null default now(),
    created_by   varchar(255),
    updated_at   timestamptz,
    updated_by   varchar(255)
);

-- Worklist ordering (most recent expense first).
create index idx_company_expense_date on company_expense (expense_date desc, id desc);
