-- V26: Salary management (production-readiness Phase 2.1).
-- (1) Additional salary fields on the applicant profile: an annual figure plus recorded
--     percentages (eligibility % and expected increment %). Money stays integer paise.
-- (2) profile_change_log — an append-only previous->new history for audited profile/salary edits.
--     Modified-by / modified-at come from the standard audit columns (created_by/created_at).
alter table applicant_profile
    add column annual_salary_paise   bigint,
    add column salary_percentage     numeric(5,2),
    add column increment_percentage  numeric(5,2);

create table profile_change_log (
    id             bigint generated by default as identity primary key,
    applicant_id   bigint        not null,
    application_id bigint,
    field          varchar(64)   not null,
    old_value      text,
    new_value      text,
    created_at     timestamptz   not null default now(),
    created_by     varchar(255),
    updated_at     timestamptz,
    updated_by     varchar(255)
);

-- History lookup for one customer, newest first.
create index idx_profile_change_log_applicant on profile_change_log (applicant_id, id desc);
