-- V27: Profile management (Phase 2.2).
-- (1) borrower_preferences — server-persisted notification opt-outs, keyed by the borrower's stable
--     applicant_id (NOT application_id) so one row survives across reborrows. Defaults: all channels on.
-- (2) applicant_profile emergency-contact fields (editable on the borrower profile; not verified).
-- (3) staff_user department / designation (editable on the staff self-profile).

create table borrower_preferences (
    id            bigint generated by default as identity primary key,
    applicant_id  bigint        not null unique,
    email_opt_in  boolean       not null default true,
    sms_opt_in    boolean       not null default true,
    offers_opt_in boolean       not null default true,
    created_at    timestamptz   not null default now(),
    created_by    varchar(255),
    updated_at    timestamptz,
    updated_by    varchar(255)
);

alter table applicant_profile
    add column emergency_contact_name     varchar(160),
    add column emergency_contact_phone    varchar(20),
    add column emergency_contact_relation varchar(60);

alter table staff_user
    add column department  varchar(120),
    add column designation varchar(120);
