-- V28: refer-a-friend program. Three FK-light tables (indexes only, integer-paise money, audit
-- columns mirror BaseAuditEntity). The durable per-person key is applicant_id (bigint) — the same
-- key carried on loan/loan_application, NOT applicant_profile.id (that table is per-application).
--
--   referral_code    one shareable code per applicant
--   referral         a captured referrer→referred relationship + its qualification state
--   referral_payout  one reward row per beneficiary (two per qualified referral); backs both the
--                    Disbursement-Head payout approval dashboard and the referral-expense view

create table referral_code (
    id           bigint generated by default as identity primary key,
    applicant_id bigint       not null,
    code         varchar(16)  not null,
    created_at   timestamptz  not null default now(),
    created_by   varchar(255),
    updated_at   timestamptz,
    updated_by   varchar(255)
);
-- One code per applicant; codes are globally unique (used for lookup on redemption).
create unique index uq_referral_code_applicant on referral_code (applicant_id);
create unique index uq_referral_code_code on referral_code (code);

create table referral (
    id                    bigint generated by default as identity primary key,
    referrer_applicant_id bigint       not null,
    referred_applicant_id bigint       not null,
    code_used             varchar(16)  not null,
    -- PENDING (signed up with a code) → QUALIFIED (referred's first loan disbursed) / REJECTED.
    status                varchar(32)  not null default 'PENDING',
    qualifying_loan_id    bigint,
    qualified_at          timestamptz,
    created_at            timestamptz  not null default now(),
    created_by            varchar(255),
    updated_at            timestamptz,
    updated_by            varchar(255)
);
-- A person can be referred at most once (idempotency + anti-abuse).
create unique index uq_referral_referred on referral (referred_applicant_id);
create index idx_referral_referrer on referral (referrer_applicant_id);
create index idx_referral_status on referral (status);

create table referral_payout (
    id                        bigint generated by default as identity primary key,
    referral_id               bigint       not null,
    beneficiary_applicant_id  bigint       not null,
    beneficiary_role          varchar(16)  not null,            -- REFERRER | REFERRED
    counterparty_applicant_id bigint,
    amount_paise              bigint       not null,            -- snapshot of the reward at creation
    status                    varchar(16)  not null default 'PENDING',  -- PENDING | PAID
    txn_ref                   varchar(64),
    paid_at                   timestamptz,
    paid_by                   varchar(255),
    qualifying_loan_id        bigint,
    created_at                timestamptz  not null default now(),
    created_by                varchar(255),
    updated_at                timestamptz,
    updated_by                varchar(255)
);
-- Approval-queue ordering (oldest pending first via the controller; index serves status filters).
create index idx_referral_payout_status on referral_payout (status, id desc);
create index idx_referral_payout_referral on referral_payout (referral_id);
create index idx_referral_payout_beneficiary on referral_payout (beneficiary_applicant_id);
