-- NAVIX Finance — core schema baseline.
--
-- Creates the tables backing the JPA entities across all business modules. The
-- column types, lengths, precision/scale and enum CHECK constraints mirror the
-- entity mappings exactly so that Hibernate's `ddl-auto: validate` passes.
--
-- Conventions:
--   * Long  ids -> bigint identity columns (GenerationType.IDENTITY).
--   * UUID  ids -> uuid columns (GenerationType.UUID, generated by the app).
--   * Audited entities (extends BaseAuditEntity) carry created_at/created_by/
--     updated_at/updated_by.
--   * Instant -> timestamp with time zone; LocalDate -> date.

-- =========================================================================
-- IAM (navix-iam)
-- =========================================================================

create table staff_user (
    id          bigint generated by default as identity,
    email       varchar(255) not null unique,
    name        varchar(255) not null,
    role        varchar(255) not null check (role in ('KYC_APPROVER','CREDIT_EXECUTIVE','CREDIT_HEAD','DISBURSEMENT_HEAD','ACCOUNTANT','COLLECTIONS_HEAD','COLLECTION_OFFICER','ADMIN')),
    status      varchar(255) not null check (status in ('ACTIVE','INVITED','DISABLED')),
    created_at  timestamp(6) with time zone not null,
    created_by  varchar(255),
    updated_at  timestamp(6) with time zone,
    updated_by  varchar(255),
    primary key (id)
);

create table staff_invite (
    id          bigint generated by default as identity,
    email       varchar(255) not null,
    role        varchar(255) not null check (role in ('KYC_APPROVER','CREDIT_EXECUTIVE','CREDIT_HEAD','DISBURSEMENT_HEAD','ACCOUNTANT','COLLECTIONS_HEAD','COLLECTION_OFFICER','ADMIN')),
    token       varchar(255) not null unique,
    expires_at  timestamp(6) with time zone not null,
    accepted_at timestamp(6) with time zone,
    created_at  timestamp(6) with time zone not null,
    created_by  varchar(255),
    updated_at  timestamp(6) with time zone,
    updated_by  varchar(255),
    primary key (id)
);

create table blocklist_entry (
    id          bigint generated by default as identity,
    type        varchar(24) not null check (type in ('PAN','AADHAAR_REF','PHONE','DEVICE','BANK_ACCOUNT')),
    value       varchar(255) not null,
    reason      varchar(255),
    active      boolean not null,
    created_at  timestamp(6) with time zone not null,
    created_by  varchar(255),
    updated_at  timestamp(6) with time zone,
    updated_by  varchar(255),
    primary key (id)
);

-- =========================================================================
-- Onboarding (navix-onboarding)
-- =========================================================================

create table borrower (
    id                bigint generated by default as identity,
    pan               varchar(10),
    mobile            varchar(15),
    personal_email    varchar(255),
    official_email    varchar(255),
    employment_status varchar(255),
    uan               varchar(12),
    declared_salary   numeric(38,2),
    salary_bank       varchar(255),
    salary_credit_day integer,
    status            varchar(255),
    created_at        timestamp(6) with time zone not null,
    created_by        varchar(255),
    updated_at        timestamp(6) with time zone,
    updated_by        varchar(255),
    primary key (id)
);

create table co_applicant (
    id               bigint generated by default as identity,
    borrower_id      bigint not null,
    pan              varchar(10),
    mobile           varchar(15),
    name             varchar(255),
    relationship     varchar(255),
    shares_repayment boolean not null,
    created_at       timestamp(6) with time zone not null,
    created_by       varchar(255),
    updated_at       timestamp(6) with time zone,
    updated_by       varchar(255),
    primary key (id)
);

create table signup_application (
    id           bigint generated by default as identity,
    borrower_id  bigint,
    current_step varchar(255) check (current_step in ('MOBILE_OTP','PERSONAL_EMAIL','OFFICIAL_EMAIL','PAN_DETAILS','EMPLOYMENT_STATUS','UAN_DETAILS','SALARY_DECLARATION','SALARY_BANK','KYC_IDENTITY','DIGILOCKER_AADHAAR','SELFIE_CAPTURE','REVIEW_SUBMIT')),
    completed    boolean not null,
    created_at   timestamp(6) with time zone not null,
    created_by   varchar(255),
    updated_at   timestamp(6) with time zone,
    updated_by   varchar(255),
    primary key (id)
);

-- =========================================================================
-- KYC (navix-kyc)
-- =========================================================================

create table kyc_case (
    id          bigint generated by default as identity,
    borrower_id bigint,
    status      varchar(255),
    created_at  timestamp(6) with time zone not null,
    created_by  varchar(255),
    updated_at  timestamp(6) with time zone,
    updated_by  varchar(255),
    primary key (id)
);

create table kyc_check (
    id          bigint generated by default as identity,
    kyc_case_id bigint,
    type        varchar(255) check (type in ('PAN','AADHAAR','SELFIE','ADDRESS')),
    result      varchar(255),
    score       numeric(38,2),
    created_at  timestamp(6) with time zone not null,
    created_by  varchar(255),
    updated_at  timestamp(6) with time zone,
    updated_by  varchar(255),
    primary key (id)
);

create table digilocker_session (
    id             bigint generated by default as identity,
    borrower_id    bigint,
    client_id      varchar(255),
    status         varchar(255),
    aadhaar_linked boolean not null,
    created_at     timestamp(6) with time zone not null,
    created_by     varchar(255),
    updated_at     timestamp(6) with time zone,
    updated_by     varchar(255),
    primary key (id)
);

-- =========================================================================
-- Income & risk (navix-income-risk)
-- =========================================================================

create table income_profile (
    id                bigint generated by default as identity,
    applicant_id      bigint not null,
    monthly_salary    numeric(14,2) not null,
    salary_credit_day integer,
    employer          varchar(255),
    uan_tenure        integer,
    primary key (id)
);

create table risk_assessment (
    id            bigint generated by default as identity,
    applicant_id  bigint not null,
    category      char(1) not null check (category in ('A','B','C','D')),
    score         integer,
    limit_granted numeric(14,2),
    factors       varchar(2000),
    primary key (id)
);

-- =========================================================================
-- Loan (navix-loan)
-- =========================================================================

create table loan (
    id                  bigint generated by default as identity,
    applicant_id        bigint not null,
    principal           numeric(14,2) not null,
    processing_fee      numeric(14,2),
    gst                 numeric(14,2),
    net_disbursed       numeric(14,2),
    daily_interest_rate numeric(6,4),
    disbursed_on        date,
    due_date            date,
    total_repayable     numeric(14,2),
    outstanding         numeric(14,2),
    status              varchar(32) not null check (status in ('APPLIED','UNDER_REVIEW','APPROVED','DOCS_SIGNED','BANK_VERIFIED','DISBURSING','ACTIVE','REPAID','OVERDUE','IN_COLLECTIONS','CLOSED','DECLINED')),
    created_at          timestamp(6) with time zone not null,
    created_by          varchar(255),
    updated_at          timestamp(6) with time zone,
    updated_by          varchar(255),
    primary key (id)
);

create table loan_application (
    id               bigint generated by default as identity,
    applicant_id     bigint not null,
    amount_requested numeric(14,2) not null,
    eligible_limit   numeric(14,2),
    status           varchar(32) not null check (status in ('APPLIED','UNDER_REVIEW','APPROVED','DOCS_SIGNED','BANK_VERIFIED','DISBURSING','ACTIVE','REPAID','OVERDUE','IN_COLLECTIONS','CLOSED','DECLINED')),
    primary key (id)
);

create table loan_document (
    id          bigint generated by default as identity,
    loan_id     bigint not null,
    type        varchar(32) not null check (type in ('AGREEMENT','SANCTION','KFS')),
    storage_uri varchar(255),
    primary key (id)
);

create table payment (
    id         bigint generated by default as identity,
    loan_id    bigint not null,
    amount     numeric(14,2) not null,
    method     varchar(24) not null check (method in ('UPI','BANK_TRANSFER','NACH')),
    status     varchar(24) not null check (status in ('PENDING_VERIFICATION','VERIFIED','REJECTED')),
    txn_ref    varchar(255),
    proof_url  varchar(255),
    paid_on    date,
    partial    boolean not null,
    created_at timestamp(6) with time zone not null,
    created_by varchar(255),
    updated_at timestamp(6) with time zone,
    updated_by varchar(255),
    primary key (id)
);

-- =========================================================================
-- Disbursement (navix-disbursement)
-- =========================================================================

create table disbursement_request (
    id         uuid not null,
    loan_id    uuid not null,
    status     varchar(255) not null check (status in ('PENDING_CREDIT_REVIEW','CREDIT_RECOMMENDED','CREDIT_APPROVED','RELEASE_AUTHORISED','TRANSFER_PENDING','TRANSFER_CONFIRMED','TRANSFER_FAILED')),
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    primary key (id)
);

create table approval_step (
    id                      uuid not null,
    disbursement_request_id uuid not null,
    role                    varchar(255) not null,
    actor_id                uuid not null,
    decision                varchar(255) not null,
    at                      timestamp(6) with time zone not null,
    primary key (id)
);

-- =========================================================================
-- Collections (navix-collections)
-- =========================================================================

create table collection_case (
    id                  uuid not null,
    loan_id             uuid not null,
    current_bucket      varchar(255),
    assigned_officer_id uuid,
    created_at          timestamp(6) with time zone not null,
    primary key (id)
);

create table interaction_log (
    id                  uuid not null,
    collection_case_id  uuid not null,
    type                varchar(255) not null,
    outcome             varchar(255) not null,
    promise_to_pay_date date,
    proof_ref           varchar(255),
    logged_at           timestamp(6) with time zone not null,
    primary key (id)
);

create table repayment_plan (
    id                 uuid not null,
    collection_case_id uuid not null,
    revised_due_date   date not null,
    proposed_by        uuid not null,
    approved_by        uuid,
    created_at         timestamp(6) with time zone not null,
    approved_at        timestamp(6) with time zone,
    primary key (id)
);

create table settlement (
    id                 uuid not null,
    collection_case_id uuid not null,
    settlement_amount  numeric(38,2) not null,
    proposed_by        uuid not null,
    approved_by        uuid,
    created_at         timestamp(6) with time zone not null,
    approved_at        timestamp(6) with time zone,
    primary key (id)
);

-- =========================================================================
-- Indexes supporting the repository finder queries.
-- =========================================================================

create index idx_blocklist_entry_type_value      on blocklist_entry (type, value);
create index idx_blocklist_entry_active          on blocklist_entry (active);
create index idx_staff_user_role                 on staff_user (role);
create index idx_staff_invite_email              on staff_invite (email);
create index idx_borrower_pan                    on borrower (pan);
create index idx_borrower_mobile                 on borrower (mobile);
create index idx_co_applicant_borrower_id        on co_applicant (borrower_id);
create index idx_signup_application_borrower_id  on signup_application (borrower_id);
create index idx_kyc_case_borrower_id            on kyc_case (borrower_id);
create index idx_kyc_check_kyc_case_id           on kyc_check (kyc_case_id);
create index idx_income_profile_applicant_id     on income_profile (applicant_id);
create index idx_risk_assessment_applicant_id    on risk_assessment (applicant_id);
create index idx_loan_applicant_id               on loan (applicant_id);
create index idx_loan_application_applicant_id   on loan_application (applicant_id);
create index idx_loan_document_loan_id           on loan_document (loan_id);
create index idx_payment_loan_id                 on payment (loan_id);
create index idx_disbursement_request_loan_id    on disbursement_request (loan_id);
create index idx_approval_step_request_id        on approval_step (disbursement_request_id);
create index idx_collection_case_loan_id         on collection_case (loan_id);
create index idx_collection_case_officer_id      on collection_case (assigned_officer_id);
create index idx_interaction_log_case_id         on interaction_log (collection_case_id);
create index idx_repayment_plan_case_id          on repayment_plan (collection_case_id);
create index idx_settlement_case_id              on settlement (collection_case_id);
