-- Dev-only, DB-backed feature flags. There is intentionally NO write API and NO admin UI for this
-- table: it is changed ONLY by a developer running SQL against the database (e.g.
--   update feature_flag set enabled = false where flag_key = 'referral';
-- The application only ever READS these rows to decide whether a feature is on. A generic
-- key/value table so new features gate by inserting a row + checking FeatureFlagService.isEnabled(key).
create table feature_flag (
    id          bigint generated by default as identity primary key,
    flag_key    varchar(80)  not null unique,           -- "flag_key" — "key" is reserved in SQL
    enabled     boolean      not null default false,
    description varchar(255),
    created_at  timestamp(6) with time zone not null default now(),
    created_by  varchar(255),
    updated_at  timestamp(6) with time zone,
    updated_by  varchar(255)
);

-- Seed the referral flag = true to preserve current behaviour (navix.referral.enabled defaults true).
insert into feature_flag (flag_key, enabled, description, created_at)
values ('referral', true, 'Refer-a-friend program: borrower codes, redemption, and reward payouts', now());
