-- V32: email suppression list — addresses we must stop emailing because SES reported a hard bounce
-- or a complaint (fed in by the SNS->SQS SesEventSqsListener). Distinct from the navix-iam
-- blocklist_entry (PAN/Aadhaar identity fraud) and from borrower channel opt-outs (a preference).
-- FK-light + enum-as-varchar per the project convention; the unique index on lower(email) makes
-- suppression idempotent and the send-time lookup case-insensitive.

create table email_suppression (
    id             bigint generated by default as identity primary key,
    email          varchar(320) not null,
    reason         varchar(16)  not null,    -- BOUNCE | COMPLAINT | MANUAL
    sub_type       varchar(60),              -- provider detail, e.g. Permanent/General
    ses_message_id varchar(160),             -- correlates to notification_delivery.provider_ref
    detail         varchar(1000),
    created_at     timestamptz  not null default now()
);

create unique index ux_email_suppression_email on email_suppression (lower(email));
create index ix_email_suppression_msg on email_suppression (ses_message_id);
