-- V34 — Password auth for borrowers + a forgot/reset framework for both audiences.
-- Borrowers were OTP-only (no password, no durable per-person row). Staff had a password but no
-- stored mobile for the email+mobile reset gate. Reset is a one-time tokenized link (we store only
-- the SHA-256 hash of the token, never the raw value).

-- 1. The borrower's password, keyed by the durable mobile-derived customer id.
create table borrower_credential (
    customer_id   bigint       primary key,
    password_hash varchar(255) not null,
    created_at    timestamptz  not null default now(),
    updated_at    timestamptz  not null default now()
);

-- 2. Staff need a stored mobile so the email+mobile forgot-password gate can match.
alter table staff_user add column if not exists mobile varchar(20);
-- Demo: give every seeded staff a known mobile so staff forgot-password is testable in the demo.
-- (Email is unique and identifies the account; the shared mobile is the documented second factor.)
update staff_user set mobile = '9000000000' where mobile is null;

-- 3. One-time password-reset tokens (store the SHA-256 HASH; the raw token rides the email link).
create table password_reset_token (
    id           bigint       generated by default as identity primary key,
    token_hash   varchar(64)  not null unique,
    subject_type varchar(10)  not null,        -- BORROWER | STAFF
    subject_id   bigint       not null,
    email        varchar(320) not null,
    expires_at   timestamptz  not null,
    used_at      timestamptz,
    created_at   timestamptz  not null default now()
);
create index idx_password_reset_token_subject on password_reset_token (subject_type, subject_id);
