create table provider_api_execution (
    id bigint generated by default as identity primary key,
    operation varchar(40) not null,
    provider varchar(40) not null,
    request_json jsonb not null,
    response_json jsonb,
    status varchar(20) not null,
    error_message varchar(2000),
    duration_ms bigint not null,
    application_id bigint,
    expires_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null,
    created_by varchar(255),
    updated_at timestamp(6) with time zone,
    updated_by varchar(255)
);
create index ix_provider_api_execution_created on provider_api_execution(created_at desc);
create index ix_provider_api_execution_expires on provider_api_execution(expires_at);
