-- NAVIX Finance — make loan_application the single application aggregate carrying the canonical
-- lifecycle (dfd.md §8), and add the append-only application_event approval/audit trail.

-- Clear throwaway demo rows from earlier smoke tests so the new status CHECK (which uses the
-- ApplicationStatus vocabulary, not the old LoanStatus one) does not reject pre-existing values.
delete from payment;
delete from loan;
delete from loan_application;

-- loan_application becomes the aggregate: swap the status vocabulary to ApplicationStatus and add
-- the lifecycle fields (purpose, assigned executive, and the link to the disbursed loan).
alter table loan_application drop constraint if exists loan_application_status_check;

alter table loan_application
    add column if not exists purpose               varchar(255),
    add column if not exists assigned_executive_id bigint,
    add column if not exists loan_id               bigint;

alter table loan_application
    add constraint loan_application_status_check check (status in (
        'DRAFT','KYC_PENDING','KYC_APPROVED','KYC_REJECTED',
        'CREDIT_EXEC_PENDING','CREDIT_EXEC_APPROVED','CREDIT_HEAD_PENDING','CREDIT_HEAD_APPROVED',
        'DISBURSEMENT_PENDING','ACCOUNTANT_PENDING','DISBURSEMENT_FAILED','DISBURSED',
        'ACTIVE','OVERDUE','DEFAULTED','CLOSED','WRITTEN_OFF','REJECTED','CANCELLED'));

create table application_event (
    id             bigint generated by default as identity,
    application_id bigint not null,
    from_status    varchar(32),
    to_status      varchar(32) not null,
    actor_id       varchar(255) not null,
    actor_role     varchar(64),
    action         varchar(64) not null,
    notes          varchar(2000),
    at             timestamp(6) with time zone not null,
    primary key (id)
);

create index idx_application_event_application_id on application_event (application_id);
create index idx_loan_application_status on loan_application (status);
