-- Bureau rescore backfill (V57+ per plan32.md/plana.md Part B): one row per application per run,
-- recording the outcome of BureauBackfillService's preview/execute pass over the sub-550 rejects,
-- credit-review, review/KYC-pending, and approved-undisbursed cohorts. No FK constraints — indexes
-- only, matching the rest of this schema (see CLAUDE.md §10 "Known DB debt").
create table bureau_backfill_row (
    id                    bigint generated by default as identity primary key,
    run_id                varchar(64)  not null,
    application_id        bigint       not null,
    customer_id           bigint       not null,
    cohort                varchar(32)  not null,
    outcome               varchar(32)  not null,           -- REOPENED, REFRESHED, STILL_BELOW, NO_BRIEF,
                                                             -- MISMATCH_REVIEW, FAILED, SKIPPED
    old_score             bigint,
    new_score             bigint,
    failed_step           varchar(32),                      -- BUREAU_PULL, PDF_INGEST, BRIEF_GENERATE,
                                                             -- REOPEN, NOTIFY
    error_code            varchar(64),
    error_detail          varchar(500),
    provider_execution_id bigint,
    attempted_at          timestamp(6) with time zone not null,
    created_at            timestamp(6) with time zone not null default now(),
    created_by            varchar(255),
    updated_at            timestamp(6) with time zone,
    updated_by            varchar(255)
);

create index idx_bureau_backfill_row_run_id on bureau_backfill_row (run_id);
create index idx_bureau_backfill_row_application_id on bureau_backfill_row (application_id);

-- Seed the Fintrix kill switch as ON, so it's discoverable in the table instead of requiring an
-- operator to know the key and INSERT it mid-incident. FintrixVerificationAdapter already defaults
-- to enabled when the row is absent (featureFlags.isEnabled("fintrix-bureau", true)); this just makes
-- the switch visible.
insert into feature_flag (flag_key, enabled, description, created_at)
values ('fintrix-bureau', true, 'Fintrix CRIF bureau pull (primary; Digitap is the fallback)', now())
on conflict (flag_key) do nothing;
