-- V77 — Skip Tracer: history of on-demand Digitap Skip Tracing Lite lookups.
--
-- Collections needs fresh contact points for a borrower who has gone quiet: alternate mobiles,
-- emails and ranked addresses. Digitap's Skip Tracing Lite returns exactly that, but every HTTP 200
-- is billed (even "no record"), so it is NEVER run by the lifecycle — a COLLECTION_HEAD or ADMIN
-- triggers it per customer from the Skip Tracer tab, and the result is kept here so every later
-- reader (customer page, loan pop-up, collections worklist) sees it without paying again.
--
-- Keyed by customer, not application: a person has one identity, so the same history shows on all
-- of their files; application_id / loan_id only record where the run was launched from. Every run
-- is kept (status SUCCESS | NO_RECORD | FAILED) with who ran it — a paid, PII-returning call must
-- leave a trail. response_json is the vendor envelope verbatim; the console renders its structure.
create table skip_trace (
    id                  bigint generated by default as identity primary key,
    customer_id         bigint       not null,
    application_id      bigint,
    loan_id             bigint,
    status              varchar(20)  not null,
    result_code         integer,
    provider_request_id varchar(64),
    message             varchar(500),
    request_json        jsonb        not null,
    response_json       jsonb,
    duration_ms         bigint,
    run_by_staff_id     bigint       not null,
    run_by_name         varchar(200),
    run_by_role         varchar(40),
    created_at          timestamptz  not null default now(),
    created_by          varchar(200),
    updated_at          timestamptz,
    updated_by          varchar(200)
);

create index idx_skip_trace_customer on skip_trace (customer_id, created_at desc);
