-- V80 — Mobile-reuse check (staff pop-up): index reference mobiles and keep the MOBILE numbers each
-- bureau report carries, so "is this number in another customer's report?" is an indexed lookup
-- instead of parsing every raw_response. Only 10-digit mobiles are stored (masked / landline numbers
-- are never matched). Rows are derived from application_verification (BUREAU) and fully rebuilt per
-- application by BureauPhoneIndexer; identity_mismatch rows are kept but excluded from matching.
create index ix_application_reference_mobile on application_reference (mobile);

create table bureau_phone (
    id                bigint generated by default as identity primary key,
    customer_id       bigint      not null,
    application_id    bigint      not null,
    mobile            varchar(10) not null,
    source            varchar(10),
    reported_date     date,
    identity_mismatch boolean     not null default false,
    pulled_at         timestamptz,
    created_at        timestamptz not null default now(),
    created_by        varchar(200),
    updated_at        timestamptz,
    updated_by        varchar(200),
    constraint uq_bureau_phone_app_mobile unique (application_id, mobile)
);
create index ix_bureau_phone_mobile on bureau_phone (mobile);
create index ix_bureau_phone_customer on bureau_phone (customer_id);
