-- V9: applicant KYC profile + uploaded documents, so staff reviewers can see who they are
-- deciding on. Both tables hang off loan_application (1:1 profile, 1:N documents). Demo-grade:
-- document bytes are stored inline as bytea (no external object store yet).

create table applicant_profile (
    id                   bigint generated by default as identity primary key,
    application_id       bigint not null,
    full_name            varchar(160),
    pan                  varchar(10),
    dob                  date,
    address              varchar(400),
    employer             varchar(160),
    employment_status    varchar(64),
    monthly_salary_paise bigint,
    salary_bank          varchar(120),
    created_at           timestamp(6) with time zone not null,
    created_by           varchar(255),
    updated_at           timestamp(6) with time zone,
    updated_by           varchar(255),
    constraint uq_applicant_profile_application unique (application_id)
);

create table application_document (
    id             bigint generated by default as identity primary key,
    application_id bigint not null,
    doc_type       varchar(64) not null,
    file_name      varchar(255) not null,
    content_type   varchar(128),
    size_bytes     bigint,
    data           bytea not null,
    created_at     timestamp(6) with time zone not null,
    created_by     varchar(255),
    updated_at     timestamp(6) with time zone,
    updated_by     varchar(255)
);

create index idx_application_document_application on application_document (application_id);
